kind: ConfigMap
apiVersion: v1
metadata:
  name: alertmanager-config
  namespace: monitoring
data:
  config.yml: |-
    global:
    templates:
    - '/etc/alertmanager/*.tmpl'
    inhibit_rules:
    - source_match:
        severity: 'critical'
        alertname: 'Prometheus down [test]'
      target_match:
        severity: 'slack'
      equal: ['instance_dg']

    route:
      receiver: alert-emailer
      group_by: ['alertname', 'priority']
      group_wait: 10s
      repeat_interval: 30m
      routes:
        - receiver: slack_demo
        # Send severity=slack alerts to slack.
          match:
            severity: slack
          group_wait: 10s
          repeat_interval: 1m
        # - receiver: pager
        # # Send severity=slack alerts to slack.
        #   match:
        #     severity: critical
        #   group_wait: 10s
        #   repeat_interval: 1m
        - receiver: slack_critical
        # Send severity=slack alerts to slack.
          match_re:
            severity: critical

          group_wait: 10s
          repeat_interval: 1m
        
 
    receivers:
    - name: alert-emailer
      email_configs:
      - to: test@test.com
        send_resolved: false
        from: from-email@email.com
        smarthost: email-host-here
        require_tls: false
    - name: slack_demo
      slack_configs:
      - api_url: https://hooks.slack.com/services/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
        channel: '#alerting'
        send_resolved: true
    # - name: pager
    #   pagerduty_configs:
    #   - service_key: LENONEONGOENo3u239aljeAHOFUH
    - name: slack_critical
      slack_configs:
      - api_url: https://hooks.slack.com/services/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
        channel: '#alerting'
        send_resolved: true
      