kind: ConfigMap
apiVersion: v1
metadata:
  name: alertmanager-config
  namespace: monitoring
data:
  config.yml: |-
    global:
    templates:
    - '/etc/alertmanager/*.tmpl'
    # inhibit_rules:
    # - source_match:
    #     severity: 'critical'
    #     alertname: 'Prometheus down [test]'
    #   target_match:
    #     severity: 'slack'
    #   equal: ['instance_dg']

    route:
      receiver: alert-emailer
      group_wait: 10s
      repeat_interval: 4h
      routes:
        - receiver: slack_demo
        # Send severity=slack alerts to slack.
          match:
            severity: slack
          group_wait: 10s
          repeat_interval: 1m
        # - receiver: pager
        # # Send severity=slack alerts to slack.
        #   match:
        #     severity: critical
        #   group_wait: 10s
        #   repeat_interval: 1m
        - receiver: slack_critical
        # Send severity=slack alerts to slack.
          match_re:
            severity: critical

          group_wait: 10s
          repeat_interval: 1m
        
 
    receivers:
    - name: alert-emailer
      email_configs:
      - to: test@test.com
        send_resolved: false
        from: from-email@email.com
        smarthost: email-host-here
        require_tls: false
    - name: slack_demo
      slack_configs:
      - api_url: https://hooks.slack.com/services/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
        channel: '#alerting'
        send_resolved: true
        title: '{{template "custom_title" .}}'
        text: '{{template "custom_slack_message" .}}'
    # - name: pager
    #   pagerduty_configs:
    #   - service_key: LENONEONGOENo3u239aljeAHOFUH
    - name: slack_critical
      slack_configs:
      - api_url: https://hooks.slack.com/services/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
        channel: '#alerting'
        send_resolved: true
        title: '{{template "custom_title" .}}'
        text: '{{template "custom_slack_message" .}}'
  notification-slack.tmpl: |
    {{ define "__single_message_title" }}{{ range .Alerts.Firing }}{{ .Labels.alertname }} @ {{ .Annotations.identifier }}{{ end }}{{ range .Alerts.Resolved }}{{ .Labels.alertname }} @ {{ .Annotations.identifier }}{{ end }}{{ end }}
    {{ define "custom_title" }}[{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ if or (and (eq (len .Alerts.Firing) 1) (eq (len .Alerts.Resolved) 0)) (and (eq (len .Alerts.Firing) 0) (eq (len .Alerts.Resolved) 1)) }}{{ template "__single_message_title" . }}{{ end }}{{ end }}
    {{ define "custom_slack_message" }}
    {{ if or (and (eq (len .Alerts.Firing) 1) (eq (len .Alerts.Resolved) 0)) (and (eq (len .Alerts.Firing) 0) (eq (len .Alerts.Resolved) 1)) }}
    {{ range .Alerts.Firing }}{{ .Annotations.description }}{{ end }}{{ range .Alerts.Resolved }}{{ .Annotations.description }}{{ end }}
    {{ else }}
    {{ if gt (len .Alerts.Firing) 0 }}
    *Alerts Firing:*
    {{ range .Alerts.Firing }}- {{ .Annotations.identifier }}: {{ .Annotations.description }}
    {{ end }}{{ end }}
    {{ if gt (len .Alerts.Resolved) 0 }}
    *Alerts Resolved:*
    {{ range .Alerts.Resolved }}- {{ .Annotations.identifier }}: {{ .Annotations.description }}
    {{ end }}{{ end }}
    {{ end }}
    {{ end }}  
      