apiVersion: apps/v1
kind: Deployment
metadata:
  name: alertmanager-2
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alertmanager-2
  template:
    metadata:
      name: alertmanager
      labels:
        app: alertmanager-2
    spec:
      containers:
      - name: alertmanager
        image: prom/alertmanager:v0.15.2
        args:
          - "--config.file=/etc/alertmanager/config.yml"
          - "--storage.path=/alertmanager"
          - "--log.level=debug"
          - "--cluster.peer=alertmanager:9094"
        ports:
        - name: alertmanager
          containerPort: 9093
        volumeMounts:
        - name: config-volume
          mountPath: /etc/alertmanager
        - name: alertmanager
          mountPath: /alertmanager
      volumes:
      - name: config-volume
        configMap:
          name: alertmanager-config2
      - name: alertmanager
        emptyDir: {}

        
        