apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-server-conf2
  labels:
    name: prometheus-server-conf2
  namespace: monitoring
data:
  prometheus.rules: |-
    groups:
    - name:  test alert
      rules:
      - alert: High Pod Memory [test]
        expr: kube_pod_container_status_ready == 1
        for: 2m
        labels:
          severity: slack
        annotations:
          identifier: '{{ $labels.instance }}'
          description: High Memory Usage
      - alert: Prometheus down [test]
        expr: up{kubernetes_pod_name=~"prometheus-deployment-[^2].*"} == 1
        for: 1m
        labels:
          severity: critical
        annotations:
          identifier: '{{ $labels.instance }}'
          description: Prometheus is down
  prometheus.yml: |-
    global:
      scrape_interval: 5s
      external_labels:
        monitor: test-infra
        replica: test-prom-1
      evaluation_interval: 5s
    rule_files:
      - /etc/prometheus/prometheus.rules
    alerting:
      alertmanagers:
      - scheme: http
        static_configs:
        - targets:
          - "alertmanager:9093"
    scrape_configs:
    - job_name: 'kubestate-metrics'
      static_configs:
        - targets: ['kube-state-metrics']
    - job_name: 'Pods'
      kubernetes_sd_configs:
      - role: pod
      relabel_configs:
      - action: labelmap
        regex: __meta_kubernetes_pod_label_(.+)
      - source_labels: [__meta_kubernetes_namespace]
        action: replace
        target_label: kubernetes_namespace
      - source_labels: [__meta_kubernetes_pod_name]
        action: replace
        target_label: kubernetes_pod_name