apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-server-conf
  labels:
    name: prometheus-server-conf
  namespace: monitoring
data:
  prometheus.rules: |-
    groups:
    - name:  test alert
      rules:
      - alert: Pod not ready [test]
        expr: kube_pod_container_status_ready == 0
        for: 2m
        labels:
          severity: slack
          team: DevOps
        annotations:
          identifier: '{{ $labels.instance }}'
          description: Pods not ready
      - alert: Prometheus down [test]
        expr: up{kubernetes_pod_name=~"prometheus-deployment-[^2].*"} == 0
        for: 1m
        labels:
          severity: critical
          team: SRE
        annotations:
          identifier: '{{ $labels.instance }}'
          description: Prometheus is down
      - alert: Kubernetes core components running
        expr: kube_deployment_status_replicas_unavailable{ namespace="kube-system"} == 0
        for: 1m
        labels:
          severity: critical
          team: SRE
        annotations:
          identifier: '{{ $labels.instance }}'
          description: Core components not running properly, values={{$value}}
  prometheus.yml: |-
    global:
      scrape_interval: 5s
      external_labels:
        monitor: test-infra
        replica: test-prom-1
      evaluation_interval: 5s
    rule_files:
      - /etc/prometheus/prometheus.rules
    alerting:
      alertmanagers:
      - scheme: http
        static_configs:
        - targets:
          - "alertmanager:9093"
          - "alertmanager-2:9093"
    scrape_configs:
    - job_name: 'kubestate-metrics'
      static_configs:
        - targets: ['kube-state-metrics']
    - job_name: 'Pods'
      kubernetes_sd_configs:
      - role: pod
      relabel_configs:
      - action: labelmap
        regex: __meta_kubernetes_pod_label_(.+)
      - source_labels: [__meta_kubernetes_namespace]
        action: replace
        target_label: kubernetes_namespace
      - source_labels: [__meta_kubernetes_pod_name]
        action: replace
        target_label: kubernetes_pod_name
      - source_labels: ['__address__']
        separator:     ':'
        regex:         '(.*):(80)'
        target_label:  '__address__'
        action: drop
      - source_labels: ['__address__']
        separator:     ':'
        regex:         '(.*):(53)'
        target_label:  '__address__'
        action: drop