apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: prometheus-deployment
  namespace: monitoring
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: prometheus-server
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus:v2.10.0
          args:
            - --storage.tsdb.path=/prometheus/
            - --storage.tsdb.retention.time=7d
            - --config.file=/etc/prometheus/prometheus.yml
            - --log.level=debug
            - --web.enable-lifecycle
            - --storage.tsdb.min-block-duration=1h
            - --storage.tsdb.max-block-duration=1h
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: prometheus-config-volume
              mountPath: /etc/prometheus/
            - name: prometheus-storage-volume
              mountPath: /prometheus/
        - name: thanos
          image: improbable/thanos:v0.4.0
          args:
            - sidecar
            - --tsdb.path=/prometheus/
            - --grpc-address=0.0.0.0:9091
            - --prometheus.url=http://localhost:9090
            - --log.level=debug
          volumeMounts:
            - name: prometheus-config-volume
              mountPath: /etc/prometheus/
            - name: prometheus-storage-volume
              mountPath: /prometheus/
      volumes:
        - name: prometheus-config-volume
          configMap:
            defaultMode: 420
            name: prometheus-server-conf
  
        - name: prometheus-storage-volume
          emptyDir: {}